### ISSUE TITLE
Cannot read property 'ApiClient' of undefined

### ISSUE THREAD

**Issue by caknowchris** [lyft/lyft-node-sdk#5]
I'm trying to import node-lyft module,When I set the defaultClient, throw an error ApiClient  undefined

import Lyft from 'node-lyft';
import config from '../../config/config';

const defaultClient = Lyft.ApiClient.instance;

const ClientAuthentication = defaultClient.authentications['Client Authentication'];
ClientAuthentication.access_token = config.lyft.client_token;

const lyft = new Lyft.PublicApi();

function getAllForLocation(req, res, next) {
  console.log("123");
}

export default { getAllForLocation };

**Comment by caknowchris** [comment]
Also PublicApi undefined

**Comment by andrewmartin** [comment]
@caknowchris Can you try using `require('node-lyft')` instead and see if that works for you? I'm drumming up how to set this up with ES6, but didn't want to block you from moving forward in the meantime.

**Comment by andrewmartin** [comment]
@caknowchris 

After digging through this a bit, I would suggest you attempt to follow the patterns set in our [example controllers](https://github.com/lyft/lyft-node-sdk/blob/master/example/controllers/api/lyft/index.js) if possible. I believe the invocation is slightly different for using `ES6` imports, but the `require` syntax used there should work.

Closing for now, but let me know if you have any questions or if it doesn't function after following our examples.
